### ISSUE TITLE
选择推送形式“[标题][内容][图片][链接]”时，显示图片获取错误

### ISSUE THREAD

**Issue by exusiai07** [SuperGuGuGu/nonebot_plugin_bili_push#10]
<img width="879" alt="image" src="https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/112692808/ce668823-ed84-4dee-b362-260465abf5b4">

**Comment by SuperGuGuGu** [comment]
能否提供一下未成功推送的动态内容截图以及对应的uid？截图报错的时候往前截几行。

**Comment by SuperGuGuGu** [comment]
请问是否尝试了升级插件的操作？目前插件的版本是多少？

**Comment by exusiai07** [comment]
> 请问是否尝试了升级插件的操作？目前插件的版本是多少？

大佬您好，插件是昨天刚刚用nb plugin下载的，版本是1.0.4，uid是161775300。
尝试的指令是最新动态+UID，报错信息如下
<img width="823" alt="image" src="https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/112692808/13a2c983-7f92-412b-8823-a9f4eea78533">
这个问题在用我自己的b站账户测试时没有出现，我的uid是40919852

**Comment by SuperGuGuGu** [comment]
目前判断是绘制样式[图片]出现问题。可以尝试将[图片]换成[绘图]，或等后续更新修复该问题。
放假在外地没有电脑，现在修不了bug，大概得过几天才能修了。

**Comment by SuperGuGuGu** [comment]
已修复
