### ISSUE TITLE
无法更新下播信息

### ISSUE THREAD

**Issue by ikarosf** [SuperGuGuGu/nonebot_plugin_bili_push#12]
经检查，发现前文live_status 的类型为str，此处判断条件错误，无法进入下播分支
`                                elif live_status == 0:
                                    message = uname + "已下播"`

**Comment by SuperGuGuGu** [comment]
已修复

**Comment by SuperGuGuGu** [comment]
`elif live_status == "0": message = uname + "已下播"`
