### ISSUE TITLE
直播接口好像有问题

### ISSUE THREAD

**Issue by chanmooo** [SuperGuGuGu/nonebot_plugin_bili_push#17]
前段时间还是正常的，这几天不能收到直播通知，动态可以正常接收

**Comment by SuperGuGuGu** [comment]
最新版有修复直播接口失效问题，请更新，并添加直播间的订阅。“/添加订阅 L1234”

**Comment by chanmooo** [comment]
> 最新版有修复直播接口失效问题，请更新，并添加直播间的订阅。“/添加订阅 L1234”

是用的最新版的，这几天才有问题

**Comment by SuperGuGuGu** [comment]
现在用的是那个版本？最新版本是1.1.12。
 
（注意，最新版的直播间订阅 需要订阅的是字母L+直播间号，uid只能订阅动态）
 
另外，可以查看一下日志是否有提示api出错等类似报错。

**Comment by chanmooo** [comment]
> 现在用的是那个版本？最新版本是1.1.12。 （注意，最新版的直播间订阅 需要订阅的是字母L+直播间号，uid只能订阅动态） 另外，可以查看一下日志是否有提示api出错等类似报错。
哦哦，我以为还是以前那样一起订阅的，不过我试了一下还是有问题（11-19 12:40:39 [INFO] nonebot_plugin_bili_push | command:添加订阅
11-19 12:40:39 [ERROR] nonebot_plugin_bili_push | 直播api出错请将此消息反馈给开
发者，liveid=405005,msg=request was banned）

**Comment by chanmooo** [comment]
1.1.11版本，没找到12版本，请问哪里有
11-19 12:47:52 [INFO] nonebot_plugin_bili_push | bili_push_command_1.1.11
11-19 12:47:52 [INFO] nonebot_plugin_bili_push | command:添加订阅
11-19 12:47:52 [ERROR] nonebot_plugin_bili_push | 直播api出错请将此消息反馈给开
发者，liveid=14654492,msg=request was banned
11-19 12:47:53 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bi
li_push, lineno=2032) running complete

**Comment by SuperGuGuGu** [comment]
pypi可以下载12版本。github上由于连接问题暂时无法上传。https://pypi.org/project/nonebot-plugin-bili-push/

**Comment by chanmooo** [comment]
> pypi可以下载12版本。github上由于连接问题暂时无法上传。https://pypi.org/project/nonebot-plugin-bili-push/

emmm还是不行
11-19 12:54:06 [INFO] nonebot_plugin_bili_push | bili_push_command_1.1.12
11-19 12:54:06 [INFO] nonebot_plugin_bili_push | command:添加订阅
11-19 12:54:07 [ERROR] nonebot_plugin_bili_push | 直播api出错请将此消息反馈给开
发者，liveid=14654492,msg=request was banned
11-19 12:54:07 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bi
li_push, lineno=2032) running complete

**Comment by SuperGuGuGu** [comment]
嗯？？？我竟没有更新？
更新了隔壁，把这给忘了。
稍等一下，我马上上传一下。

**Comment by SuperGuGuGu** [comment]
已更新1.1.13，请更新插件

**Comment by chanmooo** [comment]
辛苦啦，感谢作者
