### ISSUE TITLE
KeyError: 'origin'

### ISSUE THREAD

**Issue by huihuiismywife** [SuperGuGuGu/nonebot_plugin_bili_push#2]
定时检查后就发生这个报错了![SQU7Q)Q4 L2 KUX%MX~@Q2J_tmb](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/107234845/bb3eba79-8d98-4c66-b389-852f49a03558)

**Comment by SuperGuGuGu** [comment]
是否可以提供一下对应的用户uid，或者订阅列表？这个问题估计是转发了不支持的动态导致，我需要知道对应的动态来解决问题。在 2023年6月18日，21:16，huihuiismywife ***@***.***> 写道：﻿
定时检查后就发生这个报错了

**Comment by huihuiismywife** [comment]
原神的官号，这个是最新的一个图片，报错内容跟上边一样
![D%M0}})YYG(J{)ISM0ES J3_tmb](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/107234845/467fc2d8-ef22-4bef-b118-6761d54e10cf)

**Comment by SuperGuGuGu** [comment]
此bug尚未解决，已加入待修复列表。
可以先升级插件到（0.1.15）版本临时解决一下。新版本将会跳过出错的动态。

**Comment by SuperGuGuGu** [comment]
BUG已解决，请升级到（0.1.16）版本。

**Comment by SuperGuGuGu** [comment]
命令没问题。现在的版本号是多少？如果是0.1.16的话先升级0.1.17试试，这个跟最近版本在修改数据库格式有关。
如果17版本不行的话先等等，我明天就修。

**Comment by SuperGuGuGu** [comment]
已修复。
可在git重新下载文件，或者在2202行中将“gruopcode”改为“groupcode”。
