### ISSUE TITLE
能否添加获取直播封面或者截图的功能

### ISSUE THREAD

**Issue by RyanJiang184** [SuperGuGuGu/nonebot_plugin_bili_push#21]
如题,目前的开播通知只有一行字，不知大大能否做一个同时获取直播间封面一起发出的功能。

**Comment by SuperGuGuGu** [comment]
按照正常情况是会推送直播封面的。
麻烦提供一下配置的“推送样式”，判断问题在哪。

**Comment by RyanJiang184** [comment]
配置如下：
bilipush_push_style="[标题][链接][内容][图片]"
bilipush_waittime=30
bilipush_sleeptime=10
bilipush_maximum_send=50
bilipush_botswift=false
bilipush_emojiapi=false
bilipush_basepath="./data/bilipush"

**Comment by RyanJiang184** [comment]
突然发现最近好像正常动态也不推送了，使用指令 最新动态 ***** 后发生如下报错  ：
![aa99eb6213c02afb0520d537c850cc65](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/111217394/7e922ed8-2906-4a26-8730-c58ea206a1be)
![c1d22650305c4cd15a0ea41e359e4ea8](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/111217394/cd3796cd-6b0e-4d2d-98bb-568d20fb51e6)
也确认了实装的另一nb权限管理插件没有对其拦截，在今天更新了本插件以后没有解决

**Comment by SuperGuGuGu** [comment]
直播推送无图片问题：怀疑是那个很久都没修复的bug。过几天有电脑后我再排查问题。
如有需要可以添加“[绘图]”样式，绘图样式可正常绘制封面。

**Comment by SuperGuGuGu** [comment]
新动态不推送：新增的功能因为关闭了api而无法获取部份资源，导致绘制出错。
可以选择以下其一的解决方案：
1.退回旧版插件。
2.设置“bilipush_emojiapi=true”让插件连接到api。
3.等待插件更新。

**Comment by RyanJiang184** [comment]
> 新动态不推送：新增的功能因为关闭了api而无法获取部份资源，导致绘制出错。
> 可以选择以下其一的解决方案：
> 1.退回旧版插件。
> 2.设置“bilipush_emojiapi=true”让插件连接到api。
> 3.等待插件更新。
> 

好的，感谢作者大大，等更新了

**Comment by SuperGuGuGu** [comment]
1.1.21 修复动态无法正常绘制和推送

**Comment by SuperGuGuGu** [comment]
1.1.21 修复直播推送无图片
