### ISSUE TITLE
【无法推送】未推送的动态[]

### ISSUE THREAD

**Issue by ElaineOwO** [SuperGuGuGu/nonebot_plugin_bili_push#3]
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 已存在推送数据库，开始读取数据
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 已存在订阅数据库，开始读取数据
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 未推送的动态[]
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 已存在订阅数据库，开始读取数据
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 未推送的动态[]
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 已存在订阅数据库，开始读取数据
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 未推送的动态[]
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 已存在订阅数据库，开始读取数据
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 未推送的动态[]
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 已存在订阅数据库，开始读取数据
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 未推送的动态[]
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 已存在订阅数据库，开始读取数据
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | 未推送的动态[]
06-22 20:48:02 [INFO] nonebot_plugin_bili_push | run over

大佬帮帮QWQ

**Comment by SuperGuGuGu** [comment]
这是还没检测到新动态。
发送新动态时就会推送。

**Comment by ElaineOwO** [comment]
> 

原来是酱紫 谢谢大佬解答
