### ISSUE TITLE
输入"添加订阅"指令后，并未报错，也并未返回添加成功

### ISSUE THREAD

**Issue by AirKeen76** [SuperGuGuGu/nonebot_plugin_bili_push#4]
是否可以手动在数据库中添加，添加格式是什么呢
![image](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/117345914/83cddbe0-4d26-4ccf-8e89-c4d51ebc3384)

**Comment by SuperGuGuGu** [comment]
最新版本（0.1.20.2）已解决自定义前缀无法识别问题
