### ISSUE TITLE
07-03 21:02:30 [ERROR] nonebot_plugin_bili_push | 获取消息出错，请讲此消息反馈给开发者。动态id：812881419264065607

### ISSUE THREAD

**Issue by Fsyxr** [SuperGuGuGu/nonebot_plugin_bili_push#5]
07-03 21:02:30 [ERROR] nonebot_plugin_bili_push | 获取消息出错，请讲此消息反馈给开发者。动态id：812881419264065607

**Comment by SuperGuGuGu** [comment]
已修复，请更新到（0.1.25）再尝试关注up主

**Comment by SuperGuGuGu** [comment]
已修复，请更新到（0.1.26.1）

**Comment by Fsyxr** [comment]
![image](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/85301551/2a60097e-a6f5-4ec7-8b83-2b52a741541f)
![image](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/85301551/4896088a-29d7-4ed0-952b-1199e0f648f1)
![image](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/85301551/950daf86-c1ee-4523-ac2f-e474900eef62)
更新后推送报错

**Comment by SuperGuGuGu** [comment]
已修复，请更新到（0.1.27）

**Comment by Fsyxr** [comment]
![image](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/85301551/95ecc69d-c33a-46d9-a4f7-2398f68135c7)
更新后h还是这样欸

**Comment by SuperGuGuGu** [comment]
再次修复。请更新到（0.1.28.2）
