### ISSUE TITLE
部分动态所生成的图片高度异常

### ISSUE THREAD

**Issue by cipherkint** [SuperGuGuGu/nonebot_plugin_bili_push#6]
有的太短，有的特别长，目前我的订阅中只有这一个up的动态出现了这个情况

![QQ图片20230705220620](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/23137535/fd4850b2-8f5b-4d93-a235-2939327d368f)
![QQ图片20230705220554](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/23137535/8c1ac39b-97cf-43ac-97b8-dbfbc9575030)
![QQ图片20230705220609](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/23137535/41f9c826-0271-4e35-ae66-d567c8181c6a)

**Comment by SuperGuGuGu** [comment]
目测是这两类动态计算有问题，与uid无关。已经大概知道是那部分代码问题了。今晚修一下

**Comment by SuperGuGuGu** [comment]
已修复，请更新到0.1.26查看。

**Comment by SuperGuGuGu** [comment]
颜色不错

**Comment by cipherkint** [comment]
> 已修复，请更新到0.1.26查看。

辛苦了，但我更新试了一下，目前来看，还是会出现高度比较高的情况(´д`)
![QQ图片20230706111427](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/23137535/d288d339-8c51-4ad0-9506-7f280c7b5759)

**Comment by cipherkint** [comment]
> 已修复，请更新到0.1.26查看。

辛苦了，但我更新试了一下，目前来看，还是会出现高度比较高的情况(´д`)
![QQ图片20230706111427](https://github.com/SuperGuGuGu/nonebot_plugin_bili_push/assets/23137535/d288d339-8c51-4ad0-9506-7f280c7b5759)

**Comment by SuperGuGuGu** [comment]
貌似我没把代码更新上去。更新到0.1.26.1看看
